global:
  resolve_timeout: 5m

route:
  receiver: 'discord'
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 24h
  routes:
    # Critical은 4시간마다
    - receiver: 'discord'
      match:
        severity: critical
      group_wait: 10s
      repeat_interval: 4h

    # Warning은 하루에 한 번
    - receiver: 'discord'
      match:
        severity: warning
      repeat_interval: 24h

receivers:
  - name: 'discord'
    webhook_configs:
      - url: 'http://alertmanager-discord:9094'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
